### ISSUE TITLE
The command to install the requirements fails every time.

### ISSUE THREAD

**Issue by brendansiwik** [TheSwitchGuy/firmy#3]
I get this error.
  
Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/TuxSH/firmtool.git C:\Users\Brendan\AppData\Local\Temp\pip-zhsz7y4i-build
Cannot find command 'git'

**Comment by TheSwitchGuy** [comment]
Ah, that's because you don't have Git installed! You can install it [here](https://git-scm.com/downloads)
